apiVersion: v2
name: ueransim
description: A Helm chart to deploy UERANSIM
version: 1.1.3-1
appVersion: v3.1.3
dependencies:
- name: networks5g
  condition: createNetworks
icon: https://raw.githubusercontent.com/aligungr/UERANSIM/master/.github/logo.png
maintainers:
  - email: abderaouf.khichane@orange.com
    name: Abderaouf KHICHANE
  - email: ilhem.fajjari@orange.com
    name: Ilhem FAJJARI
