{{- if .Values.nssf.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nssf.service.name }}
  labels:
    project: {{ .Values.global.projectName }}
    nf: {{ .Values.nssf.name }}
spec:
  ports:
    - port: {{ .Values.nssf.port }}
  selector:
    project: {{ .Values.global.projectName }}
    nf: {{ .Values.nssf.name }}
{{- end }}
