{{- if .Values.ausf.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ausf.configmap.name }}
  labels:
    app: {{ .Values.global.projectName }}
data:
  ausfcfg.conf: |
    info:
      version: 1.0.0
      description: AUSF initial local configuration
    
    configuration:
      sbi:
        scheme: {{ .Values.global.sbi.scheme }}
        registerIPv4: {{ .Values.ausf.service.name }} # IP used to register to NRF
        bindingIPv4: 0.0.0.0  # IP used to bind the service
        port: {{ .Values.ausf.port }}
      serviceNameList:
        - nausf-auth
      nrfUri: {{ .Values.global.sbi.scheme }}://{{ .Values.nrf.service.name }}:{{ .Values.nrf.port }}
      plmnSupportList:
        - mcc: 208
          mnc: 93
        - mcc: 123
          mnc: 45
      groupId: ausfGroup001
{{- end }}
