{{- if .Values.ue.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ue.configmap.name }}
  labels:
    app: {{ .Values.projectName }}
    component: {{ .Values.ue.name }}
data:
  ue-config.yaml: |

{{- toYaml .Values.ue.configuration | nindent 4 }}
    
    # List of gNB IP addresses for Radio Link Simulation
    gnbSearchList:
      - {{ .Values.gnb.service.name }}

  wrapper.sh: |
    #!/bin/bash

    mkdir /dev/net
    mknod /dev/net/tun c 10 200

    {{ .Values.ue.command }} 

{{ .Values.ue.script | nindent 4 }}


{{- end }}
