{{- if eq .Values.global.userPlaneArchitecture "ulcl" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.upfb.configmap.name }}
  labels:
    app: {{ .Values.global.projectName }}
data:
  upfcfgb.yaml: |
    info:
      version: 1.0.0
      description: UPF configuration
    
    configuration:
      # debugLevel: panic|fatal|error|warn|info|debug|trace
      debugLevel: info
    
      pfcp:
{{- if not .Values.global.upf.service.pfcp.enabled }}
        - addr: {{ .Values.global.upfb.n4if.ipAddress }}
{{- else }}
        - addr: 0.0.0.0
{{- end }}
    
      gtpu:
        - addr: {{ .Values.global.upfb.n3if.ipAddress }}
        # [optional] gtpu.name
        # - name: upf.5gc.nctu.me
        # [optional] gtpu.ifname
        # - ifname: gtpif
    
      dnn_list:
        - dnn: {{ .Values.global.datanetworks.dn1 }}
          cidr: {{ .Values.global.uesubnet1 }}
        #- dnn: {{ .Values.global.upf2.n3if.ipAddress }}
        #  cidr: {{ .Values.global.uesubnet2 }}
          # [optional] apn_list[*].natifname
          # natifname: eth0

  wrapper.sh: |
    #!/bin/bash

    /free5gc/free5gc-upfd/free5gc-upfd -f /free5gc/config/upfcfg.yaml

{{- end }}

