{{- if .Values.smf.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.smf.service.name }}
  labels:
    project: {{ .Values.global.projectName }}
    nf: {{ .Values.smf.name }}
spec:
  ports:
    - port: {{ .Values.smf.port }}
  selector:
    project: {{ .Values.global.projectName }}
    nf: {{ .Values.smf.name }}
{{- end }}
