{{- if .Values.ovn4nfv.enabled }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .Values.ovn4nfv.name }}
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "ovn4nfvk8s-cni"
    }'
{{- end }}
