{{- if .Values.n3iwf.enabled }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .Values.n3iwf.ike.name }}
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "eth0",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "subnet": "{{ .Values.n3iwf.ike.prefixIP }}.0/24",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "{{ .Values.n3iwf.ike.prefixIP }}.1"
      }
    }'
{{- end }}
