{{- if .Values.webui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webui.service.name }}
  labels:
    project: {{ .Values.global.projectName }}
    app: {{ .Values.webui.name }}
spec:
  type: {{ .Values.webui.service.type }}
  ports:
    - port: {{ .Values.webui.port }}
      nodePort: {{ .Values.webui.service.nodePort }}
  selector:
    project: {{ .Values.global.projectName }}
    app: {{ .Values.webui.name }}
{{- end }}
