{{- if .Values.nrf.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nrf.configmap.name }}
  labels:
    app: {{ .Values.global.projectName }}
data:
  nrfcfg.conf: |
    info:
      version: 1.0.0
      description: NRF initial local configuration
    
    configuration:
      MongoDBName: "free5gc"
      MongoDBUrl: "mongodb://{{ .Values.mongodb.service.name }}:{{ .Values.mongodb.service.port }}"
      DefaultServiceIP: "{{ .Values.nrf.service.name }}"
      sbi:
        scheme: {{ .Values.global.sbi.scheme }}
        ipv4Addr: 0.0.0.0
        port: {{ .Values.nrf.port }}
      DefaultPlmnId:
        mcc: "208"
        mnc: "93"
      serviceNameList:
        - nnrf-nfm
        - nnrf-disc
{{- end }}

