{{- if and .Values.amf.enabled (.Values.global.amf.service.ngap.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.amf.service.ngap.name }}
  labels:
    project: {{ .Values.global.projectName }}
    nf: {{ .Values.amf.name }}
spec:
  type: {{ .Values.global.amf.service.ngap.type }}
  ports:
    - name: n2
      port: {{ .Values.global.amf.service.ngap.port }}
      nodePort: {{ .Values.global.amf.service.ngap.nodeport }}
      protocol: {{ .Values.global.amf.service.ngap.protocol }}
  selector:
    project: {{ .Values.global.projectName }}
    nf: {{ .Values.amf.name }}
{{- end }}

