{{- if .Values.pcf.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.pcf.configmap.name }}
  labels:
    app: {{ .Values.global.projectName }}
data:
  pcfcfg.yaml: |
    info:
      version: 1.0.0
      description: PCF initial local configuration
    
    configuration:
      pcfName: PCF
      sbi:
        scheme: {{ .Values.global.sbi.scheme }}
        registerIPv4: {{ .Values.pcf.service.name }} # IP used to register to NRF
        bindingIPv4: 0.0.0.0  # IP used to bind the service
        port: {{ .Values.pcf.port }}
      timeFormat: 2019-01-02 15:04:05
      defaultBdtRefId: BdtPolicyId-
      nrfUri: {{ .Values.global.sbi.scheme }}://{{ .Values.nrf.service.name }}:{{ .Values.nrf.port }}
      serviceList:
        - serviceName: npcf-am-policy-control
        - serviceName: npcf-smpolicycontrol
          suppFeat: 3fff
        - serviceName: npcf-bdtpolicycontrol
        - serviceName: npcf-policyauthorization
          suppFeat: 3
        - serviceName: npcf-eventexposure
        - serviceName: npcf-ue-policy-control

      mongodb:       # the mongodb connected by this PCF
        name: free5gc                  # name of the mongodb
        url: mongodb://{{ .Values.mongodb.service.name }}:{{ .Values.mongodb.service.port }} # a valid URL of the mongodb
    
    # the kind of log output
      # debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
      # ReportCaller: enable the caller report or not, value: true or false
    logger:
      PCF:
        debugLevel: info
        ReportCaller: false
      PathUtil:
        debugLevel: info
        ReportCaller: false
      OpenApi:
        debugLevel: info
        ReportCaller: false
{{- end }}

