#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- with .Values.udm }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open5gs-udm.fullname" $ }}-configmap
  labels:
    app: {{ $.Values.global.projectName }}
data:
  udm.yaml: |
    {{- .configuration.global | nindent 4 }}

    sbi:
      server:
        no_tls: {{ .configuration.tls.server.no_tls }}
        cacert: {{ .volume.mount }}/tls/ca.crt
        key: {{ .volume.mount }}/tls/udm.key
        cert: {{ .volume.mount }}/tls/udm.crt
      client:
        no_tls: {{ .configuration.tls.client.no_tls }}
        cacert: {{ .volume.mount }}/tls/ca.crt
        key: {{ .volume.mount }}/tls/udm.key
        cert: {{ .volume.mount }}/tls/udm.crt

    udm:
          {{- .configuration.udm | nindent 10 }}

          hnet:
            {{- toYaml .configuration.hnet | nindent 12 }}

          sbi:
            - dev: eth0
              advertise: {{ include "open5gs-udm.fullname" $ }}-service
              port: {{ .service.port }}

    nrf:
          sbi:
            - addr: {{ $.Values.global.nrf.service.name }}
              port: {{ $.Values.global.nrf.service.port }}

    scp:
          sbi:
            - addr: {{ $.Values.global.scp.service.name }}
              port: {{ $.Values.global.scp.service.port }}

    logger:
      {{- .configuration.logger | nindent 6 }}

{{- end }}
