{{- if .Values.nrf.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nrf.configmap.name }}
  labels:
    app: {{ .Values.global.projectName }}
data:
  nrfcfg.yaml: |
    info:
      version: 1.0.0
      description: NRF initial local configuration
    
    configuration:
      MongoDBName: free5gc
      MongoDBUrl: mongodb://{{ .Values.mongodb.service.name }}:{{ .Values.mongodb.service.port }}
      sbi:
        scheme: {{ .Values.global.sbi.scheme }}
        registerIPv4: {{ .Values.nrf.service.name }} # IP used to serve NFs or register to another NRF
        bindingIPv4: 0.0.0.0  # IP used to bind the service
        port: {{ .Values.nrf.port }}
      DefaultPlmnId:
        mcc: 208
        mnc: 93
      serviceNameList:
        - nnrf-nfm
        - nnrf-disc
    
    logger:
      NRF:
        debugLevel: info
        ReportCaller: false
      PathUtil:
        debugLevel: info
        ReportCaller: false
      OpenApi:
        debugLevel: info
        ReportCaller: false
      MongoDBLibrary:
        debugLevel: info
        ReportCaller: false
{{- end }}

