#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
# Default values for upg-vpp chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


global:
  projectName: upgvpp
  uesubnet: 10.1.0.0/16
  smf:
    n4if:
      ipAddress: 10.100.50.244
  gnb:
    n3if:  # GTP-U
      ipAddress: 10.100.50.236
  #Global network parametes
  n4network:
    name: n4network
    masterIf: eth0
    subnetIP: 10.100.50.240
    cidr: 29
    gatewayIP: 10.100.50.246
    excludeIP: 10.100.50.246
  n3network:
    name: n3network
    masterIf: eth0
    subnetIP: 10.100.50.232
    cidr: 29
    gatewayIP: 10.100.50.238
    excludeIP: 10.100.50.238
  n6network:
    name: n6network
    masterIf: eth1
    subnetIP: 10.100.100.0
    cidr: 24
    gatewayIP: 10.100.100.1
    excludeIP: 10.100.100.254
  n9network:
    name: n9network
    masterIf: eth0
    subnetIP: 10.100.50.224
    cidr: 29
    gatewayIP: 10.100.50.230
    excludeIP: 10.100.50.230

upf:
  name: upf
  replicaCount: 1
  image:
    name: raoufkh063/upg-vpp
    pullPolicy: IfNotPresent
  configmap:
    name: upf-configmap
  volume:
    name: upf-volume
    mount: /upg-vpp/etc/

  # network paramters
  n3if:  # GTP-U
    ipAddress: 10.100.50.233
  n4if:  # PFCP
    ipAddress: 10.100.50.241
  n6if:  # DN
    ipAddress: 10.100.100.12

  podAnnotations: {}
    # additional annotations
  imagePullSecrets: []
  podSecurityContext: {}
  securityContext:
    privileged: true
    capabilities:
      add: ["NET_ADMIN"]
  resources:
    limits:
      hugepages-2Mi: 512Mi
      cpu: 3
      memory: 6Gi
    requests:
      hugepages-2Mi: 512Mi
      cpu: 3
      memory: 512Mi
  readinessProbe:
    initialDelaySeconds: 0
    periodSeconds: 1
    timeoutSeconds: 1
    failureThreshold:  40
    successThreshold: 1
  livenessProbe:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 3
    successThreshold: 1
  nodeSelector: {}
  tolerations: []
  affinity: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  configuration:
    configuration: {}
      
