{{- if .Values.amf.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.amf.configmap.name }}
  labels:
    app: {{ .Values.global.projectName }}
data:
  amfcfg.conf: |
    info:
      version: 1.0.0
      description: AMF initial local configuration
    
    configuration:
      amfName: AMF
      ngapIpList:
{{- if .Values.global.amf.service.ngap.enabled }}
        - 0.0.0.0
{{- else }}
        - {{ .Values.global.amf.n2if.ipAddress }}
{{- end }}
      sbi:
        scheme: {{ .Values.global.sbi.scheme }}
        registerIPv4: {{ .Values.amf.service.name }} # IP used to register to NRF
        bindingIPv4: 0.0.0.0  # IP used to bind the service
        port: {{ .Values.amf.port }}
      serviceNameList:
        - namf-comm
        - namf-evts
        - namf-mt
        - namf-loc
      servedGuamiList:
        - plmnId:
            mcc: 208
            mnc: 93
          amfId: cafe00
      supportTaiList:
        - plmnId:
            mcc: 208
            mnc: 93
          tac: 1
      plmnSupportList:
        - plmnId:
            mcc: 208
            mnc: 93
          snssaiList:
            - sst: 1
              sd: 010203
            - sst: 1
              sd: 112233
      supportDnnList:
        - {{ .Values.global.datanetworks.dn1 }}
{{- if eq .Values.global.userPlaneArchitecture "ulcl" }}
        - {{ .Values.global.datanetworks.dn2 }}
{{- end }}
      nrfUri: {{ .Values.global.sbi.scheme }}://{{ .Values.nrf.service.name }}:{{ .Values.nrf.port }}
      security:
        integrityOrder:
          - NIA2
          - NIA0
        cipheringOrder:
          - NEA2
          - NEA0
      networkName:
        full: free5GC
        short: free
      t3502: 720
      t3512: 3600
      non3gppDeregistrationTimer: 3240
{{- end }}
