{{- if .Values.amf.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.amf.service.name }}
  labels:
    project: {{ .Values.global.projectName }}
    nf: {{ .Values.amf.name }}
spec:
  ports:
    - port: {{ .Values.amf.port }}
  selector:
    project: {{ .Values.global.projectName }}
    nf: {{ .Values.amf.name }}
{{- end }}
